# docker-compose.yml
version: '3.9'

services:
  postgres:
    image: "postgres:latest"
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: illustrious
      POSTGRES_DB: illustrious
    ports:
      - "5432:5432"
