apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlOVEF4TURjdwpOekF6TlRGYUZ3MDBOVEF4TURjd056QXpOVEZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDdXM0M2JkcWJCcmpSOUhrMTh0M1VhM0N0SGU5UEpndUUzby9aMFhkSktUSUswZ3pjeApid2JKci9tR1NZbWhTMnNmdnViM1JCT0dscDRPV2djN3VvUnhzcy9XaEFOVzZNRTFPUjRzemlpalRsQktyTytQCnIzY0ZzeVB4YTk0RkxrY3JmZkR1MTZSYWQvczlNTUZEU2xPcndBTVVLK0t0WmpUWmhNaUJmdnVEWW9HU2lmbCsKMUcvc1dhZnhTNmRYUnBVbWRTdk5KbkVFZHpHQlRGUUhtLytTNGFXK2lqd1B3RjRGbGM5YzZVYUFUa1hKU0U2bQpya2FtczhwV1MyTlExSm51V2F1bzZJYXMvOTRpQ2o4YmU0QkdQdzVwdVpQb0FrbzQxWXNvUnljdjljT1hlQ3hFCnNscmcvODNyMUh4Q0FaVkF0eEg0QzMxZ20rRHd3Nk95Y0JkeEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlJiNEtrMFJVQ2RmeVA5KytHRQpNeUN1emN1b3h6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFMMmhxbHZqY3Boc3BWSitUV3hMU25OS3Q5dXdwCmdXQ01aZkE5SDZLWkxTd2hib05PdWZNNVFwYVNyTGRZVVY1S0drZEJyaFd6WHI3NlhlVGExR3JQUFNBdkxwNVUKWE5sRlJud3BKTk5JYUw3SlJZV3VURGVvVHluR2lHZVNsNVNzbEJad2pTNkNjcDVmZXozRkFpb2pvcDJsS2JVbApxcDF3cy9OUFhvKzB4eStLSjRpNWNHMjhJdjhnTWJiS092OG4yUlVCM2x3YTluak9yWjUzNS8rM3BTSFQzdGdhCmRuM0U0SkdIS0MyTjU4WWVKZVVtYkpFdmI4dy9KWGRKdmgvWmtHVytnK0lsSDNDQ0F4emoxZ1ZtZUsvUGhsU0MKUXFJREYyV0Y0bTdRMTVQUWlRT2RqTUhiWW5GdU5xY1N0NG51c3l4TTFpaUlqZGEvUE83T0VlWWwvdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://4fd6fa85-a34b-4946-848a-f0e58e967f6e.k8s.ondigitalocean.com
  name: do-nyc3-illustrious-cluster
contexts:
- context:
    cluster: do-nyc3-illustrious-cluster
    user: do-nyc3-illustrious-cluster-admin
  name: do-nyc3-illustrious-cluster
current-context: do-nyc3-illustrious-cluster
users:
- name: do-nyc3-illustrious-cluster-admin
  user:
    token: dop_v1_eb5478312af5391e05eaf8a63cffed4c5730bd08e9009fea0e3bf77b03aa2730
