# docker-compose.yml
version: '3.9'

services:
  app:
    image: "oven/bun"
    entrypoint: []
    command: "/bin/sh -c 'bun install && bun run --watch src/apindexp.ts'"
    ports: ["8000:8000"]
    volumes: ["./:/home/bun/app"]