name: "[ill.components] Perform release"
on:
  pull_request_review:
    types:
      - submitted
    branches:
      - main
    paths:
      - 'packages/ui/**'
jobs:
  ui-check-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Build application
        run: bun build
      - name: Run unit tests
        run: bunx turbo test --filter=@repo/ui
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ill-ui
          files: ./packages/ui/coverage/lcov-report/index-lcov.html
          slug: Illustrious-Online/illustrious.online
      - name: Publish package
        run: npm publish
        working-directory: packages/ui
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Execute Semantic Release
        working-directory: packages/ui
        run: bunx semantic-release
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add apps/ill.cloud/package.json
          git commit -m "chore(release): [ill.cloud] update version and changelog [skip ci]"
          git push origin main