name: Execute checks & tests
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'packages/ui/**'
    paths_ignore:
      - 'packages/ui/package.json'
jobs:
  check-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Build application
        run: bun build
      - name: Publish package
        run: npm publish
        working-directory: packages/ui
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Execute Semantic Release
        run: |
          cd apps/ill.cloud
          bunx semantic-release
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add apps/ill.cloud/package.json
          git commit -m "chore(release): [ill.cloud] update version and changelog [skip ci]"
          git push origin main