name: "[ill.components] Perform release"
on:
  push:
    branches:
      - main
    paths:
      - 'packages/ui/**'
      - '!packages/ui/CHANGELOG.md'
jobs:
  ui-check-and-test:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Build application
        run: bun build
      - name: Run unit tests
        run: bunx turbo test --filter=@repo/ui
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ill-ui
          files: ./packages/ui/coverage/lcov-report/index-lcov.html
          slug: Illustrious-Online/illustrious.online
      - name: Create and apply changeset
        run: |
          bunx changeset version

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "chore(release): [ill.ui] update version and changelog [skip ci]"
          git push origin main

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./packages/ui/dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish new version
        run: |
          bunx changeset publish