name: Perform release
on:
  push:
    branches:
      - main
    paths:
      - 'apps/ill.web/**'
    paths_ignore:
      - 'apps/ill.web/package.json'
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Dependencies
        run: bun install --frozen-lockfile
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Build Docker image
        run: |
          bunx turbo run build --filter=ill.web
          docker build -t ${{ secrets.REGISTRY_URL }}/ill-web:latest -f packages/deployment/docker/web.Dockerfile .
      - name: Authenticate with DO registry
        run: doctl registry login --expiry-seconds 1200
      - name: Push Docker Container
        run: docker push ${{ secrets.REGISTRY_URL }}/ill-web:latest
      - name: Execute Semantic Release
        run: |
          cd apps/ill.web
          bunx semantic-release
      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git add apps/ill.web/package.json
          git commit -m "chore(release): [ill.web] update version and changelog [skip ci]"
          git push origin main